// Copies everything in ./assets-in into ./public and writes src/assets.ts,
// a typed manifest of what actually exists. Components read the manifest so
// a missing SFX or logo degrades to its placeholder instead of 404-ing the
// render.
//
//   node scripts/scan-assets.mjs

import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const IN = path.join(ROOT, 'assets-in');
const PUB = path.join(ROOT, 'public');

const SFX_NAMES = ['stamp', 'whoosh', 'connect', 'slam', 'rise'];
const SFX_EXTS = ['.wav', '.mp3', '.m4a', '.aac', '.ogg'];
const LOGO_CANDIDATES = ['logo.svg', 'logo.png', 'logo.webp'];

fs.mkdirSync(PUB, {recursive: true});
fs.mkdirSync(path.join(PUB, 'sfx'), {recursive: true});

const copyIfPresent = (rel) => {
	const from = path.join(IN, rel);
	if (!fs.existsSync(from)) return false;
	const to = path.join(PUB, rel);
	fs.mkdirSync(path.dirname(to), {recursive: true});
	fs.copyFileSync(from, to);
	return true;
};

const notes = [];

/* voice-over ------------------------------------------------------- */
const hasVo = copyIfPresent('vo.mp3') || fs.existsSync(path.join(PUB, 'vo.mp3'));
if (!hasVo) notes.push('vo.mp3 MISSING — beats.ts falls back to the §4 timing table');

/* music ------------------------------------------------------------ */
const hasMusic = copyIfPresent('music.mp3') || fs.existsSync(path.join(PUB, 'music.mp3'));
if (!hasMusic) {
	notes.push(
		'music.mp3 MISSING — the <Audio> music slot in src/audio/Soundtrack.tsx is ' +
			'wired but inert (TODO there). Drop a licensed 20s+ bed into ' +
			'assets-in/music.mp3 and re-run this script.',
	);
}

/* sfx -------------------------------------------------------------- */
const sfx = {};
for (const name of SFX_NAMES) {
	let found = null;
	for (const ext of SFX_EXTS) {
		const rel = path.join('sfx', name + ext);
		if (copyIfPresent(rel) || fs.existsSync(path.join(PUB, rel))) {
			found = `sfx/${name}${ext}`;
			break;
		}
	}
	sfx[name] = found;
	if (!found) notes.push(`sfx/${name}.wav MISSING — slot wired, nothing rendered`);
}

/* logo ------------------------------------------------------------- */
let logo = null;
for (const cand of LOGO_CANDIDATES) {
	if (copyIfPresent(cand) || fs.existsSync(path.join(PUB, cand))) {
		logo = cand;
		break;
	}
}
if (!logo) notes.push('logo.svg/.png MISSING — using the typographic wordmark');

/* brand ------------------------------------------------------------ */
let brand = null;
const brandPath = path.join(IN, 'brand.json');
if (fs.existsSync(brandPath)) {
	try {
		brand = JSON.parse(fs.readFileSync(brandPath, 'utf8'));
		copyIfPresent('brand.json');
	} catch (err) {
		notes.push(`brand.json present but unparseable (${err.message}) — using §3 palette`);
		brand = null;
	}
} else {
	notes.push('brand.json MISSING — using the §3 palette');
}

/* write ------------------------------------------------------------ */
const body = `/* GENERATED by scripts/scan-assets.mjs — do not edit by hand.
 *
 * Re-run \`node scripts/scan-assets.mjs\` after dropping files into
 * assets-in/. Components branch on this manifest so a missing asset
 * degrades to its placeholder rather than failing the render.
 */

import type {Brand} from './theme';

export type SfxName = ${SFX_NAMES.map((n) => `'${n}'`).join(' | ')};

export const ASSETS = {
	vo: ${hasVo ? "'vo.mp3'" : 'null'} as string | null,
	music: ${hasMusic ? "'music.mp3'" : 'null'} as string | null,
	sfx: {
${SFX_NAMES.map((n) => `\t\t${n}: ${sfx[n] ? `'${sfx[n]}'` : 'null'},`).join('\n')}
	} as Record<SfxName, string | null>,
	logo: ${logo ? `'${logo}'` : 'null'} as string | null,
	brand: ${brand ? JSON.stringify(brand) : 'null'} as Brand | null,
} as const;

/** Human-readable list of what is still a placeholder. */
export const ASSET_NOTES: string[] = ${JSON.stringify(notes, null, 1).replace(/\n/g, '\n')};
`;

fs.writeFileSync(path.join(ROOT, 'src', 'assets.ts'), body);

console.log('[assets] wrote src/assets.ts');
for (const n of notes) console.log('  •', n);
if (notes.length === 0) console.log('  • all inputs present');
