// Generates out/README.md from the actual timing map and asset manifest,
// so the handover doc can never drift from the spot.
//
//   node scripts/write-readme.mjs

import path from 'node:path';
import fs from 'node:fs';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';

const ROOT = process.cwd();
const FPS = 30;

const bundleAndImport = async (entry, name) => {
	const tmp = path.join(ROOT, 'node_modules', '.cache', `${name}.mjs`);
	await build({
		entryPoints: [path.join(ROOT, entry)],
		outfile: tmp,
		bundle: true,
		format: 'esm',
		platform: 'node',
		logLevel: 'error',
	});
	return import(pathToFileURL(tmp).href + `?v=${fs.statSync(tmp).mtimeMs}`);
};

const beats = await bundleAndImport('src/timing/beats.ts', 'beats-doc');
const assets = await bundleAndImport('src/assets.ts', 'assets-doc');
const voWords = JSON.parse(
	fs.readFileSync(path.join(ROOT, 'src', 'timing', 'vo-words.json'), 'utf8'),
);

const {t, LEAD, END_HOLD, TOTAL_SEC, timingSource, timingMissed} = beats;
const {ASSETS, ASSET_NOTES} = assets;
const w = beats.beatWindows(FPS);

const f = (sec) => Math.round(sec * FPS);
const fmt = (sec) => `${sec.toFixed(3)}s`;

const SYNC_DOC = [
	['forty', '"forty" — the stamp slams on', 'Beat 1'],
	['percent', '"percent" — the % flickers', 'Beat 1'],
	['fault', '"at fault" — AT FAULT stamps beneath', 'Beat 1'],
	['opening', '"opening" — the gold strike-through cuts across', 'Beat 2'],
	['position', '"position"', 'Beat 2'],
	['not', '"not" — warm edge enters, the stamp shatters', 'Beat 2'],
	['finding', '"legal finding" — NOT A LEGAL FINDING + gold rule', 'Beat 2'],
	['awesome', '"Awesome Attorneys" — wordmark reveals', 'Beat 3'],
	['attorneys', '"Attorneys"', 'Beat 3'],
	['matches', '"matches" — YOU / ATTORNEY slide in, line draws', 'Beat 3'],
	['directly', '"directly" — the middlemen vanish, line snaps straight', 'Beat 3'],
	['phoenix', '"Phoenix" — sun completes its rise, pin drops', 'Beat 3'],
	['injury', '"injury attorney" — the chip appears', 'Beat 3'],
	['attorney', '"attorney"', 'Beat 3'],
	['getMatched', '"Get Matched" — first slam + camera punch', 'Beat 4'],
	['matched', '"Matched"', 'Beat 4'],
	['getPaid', '"Get Paid" — second slam', 'Beat 4'],
	['paid', '"Paid"', 'Beat 4'],
	['url', '"AwesomeAttorneys dot com" — lines lift, URL wipes in', 'Beat 4'],
	['end', 'last spoken word ends — end card begins', 'End card'],
];

const syncRows = SYNC_DOC.map(([key, what, beat]) => {
	const sec = t[key];
	const frame = f(sec);
	const hit = key === 'end' ? frame : frame - LEAD;
	return `| \`t.${key}\` | ${beat} | ${what} | ${fmt(sec)} | ${frame} | ${hit} |`;
}).join('\n');

const wordRows = voWords.words
	.map(
		(x) =>
			`| ${x.word} | ${(x.startMs / 1000).toFixed(3)}s | ${(x.endMs / 1000).toFixed(3)}s | ${Math.round(
				(x.startMs / 1000) * FPS,
			)} |`,
	)
	.join('\n');

const placeholderRows = ASSET_NOTES.length
	? ASSET_NOTES.map((n) => `- ${n}`).join('\n')
	: '- none — every input in §2 was supplied.';

const md = `# Awesome Attorneys — "40% At Fault"

Four rendered deliverables and two thumbnails, all built from
\`src/\` in this project. Nothing here is hand-timed: every hit is
derived from the voice-over.

Generated by \`node scripts/write-readme.mjs\`.

---

## 1. What each file is

| File | Size | Format | Where it goes |
|---|---|---|---|
| \`aa40_9x16.mp4\` | 1080×1920, 30 fps, H.264 CRF 16, AAC 320k | full spot with audio | **Reels · TikTok · Shorts** — the primary cut |
| \`aa40_16x9.mp4\` | 1920×1080, 30 fps, H.264 CRF 16, AAC 320k | full spot with audio | **YouTube · site hero · pre-roll** |
| \`aa40_9x16_alpha.mov\` | 1080×1920, ProRes 4444, \`yuva444p10le\` | transparent, **no audio** | drop over B-roll in Premiere / Resolve / Final Cut |
| \`aa40_9x16_alpha.webm\` | 1080×1920, VP9, \`yuva420p\`, \`alpha_mode=1\` | transparent, **no audio** | drop over B-roll in CapCut / browser |
| \`aa40_16x9_alpha.mov\` | 1920×1080, ProRes 4444, \`yuva444p10le\` | transparent, **no audio** | as above, landscape |
| \`aa40_16x9_alpha.webm\` | 1920×1080, VP9, \`yuva420p\`, \`alpha_mode=1\` | transparent, **no audio** | as above, landscape |
| \`thumb_9x16.png\` / \`thumb_16x9.png\` | end-card still at frame ${f(t.end + 1.4)} (${fmt(t.end + 1.4)}) | poster frame | thumbnail / still ad |

**Overlay mode** drops the background, the vignette, the film grain and all
audio, and switches every piece of type to a two-part shadow so it survives
being composited over unknown footage. The horizon *fills* (sun disc, ridge
silhouettes) are kept; the sky gradient behind them is not.

Duration for all four compositions: **${fmt(TOTAL_SEC)} = ${f(TOTAL_SEC)} frames**
(last spoken word at ${fmt(t.end)} plus a ${END_HOLD}s end-card hold).

---

## 2. Sync points

Timing source: **${timingSource}**${
	timingMissed.length ? ` (anchors filled by interpolation: ${timingMissed.join(', ')})` : ''
}.

\`LEAD = ${LEAD}\` frames: every visual hit and every SFX fires \`LEAD\` frames
*before* its word. Sound and picture slightly anticipate speech — that is what
makes the sync feel tight.

| Sync point | Beat | What happens | Word at | Word frame | Hit frame |
|---|---|---|---|---|---|
${syncRows}

### Beat windows

| Beat | From | To |
|---|---|---|
| 1 — The verdict that isn't | ${fmt(w.one.start)} | ${fmt(w.one.end)} |
| 2 — Reframe | ${fmt(w.two.start)} | ${fmt(w.two.end)} |
| light sweep transition | ${fmt(w.sweep.start)} | ${fmt(w.sweep.end)} |
| 3 — The match | ${fmt(w.three.start)} | ${fmt(w.three.end)} |
| 4 — CTA (hard cut) | ${fmt(w.four.start)} | ${fmt(w.four.end)} |

Beats 1 and 2 are one continuous scene: beat 2 transforms beat 1's frame in
place rather than replacing it.

### Full transcript, as timed

| Word | Start | End | Start frame |
|---|---|---|---|
${wordRows}

---

## 3. Placeholders still in use

${placeholderRows}

The wordmark currently renders typographically — AWESOME in white,
ATTORNEYS in gold, tracked +0.16em. Drop \`assets-in/logo.svg\` or
\`logo.png\` (transparent) and re-run \`node scripts/scan-assets.mjs\` to
swap it in everywhere; nothing else needs editing.

Disclaimer wording is a prop, not a constant. It currently reads
*"Attorney matching service. Not a law firm. Not legal advice."* — override
per render with:

\`\`\`bash
npx remotion render AA40-9x16 out/aa40_9x16.mp4 --codec=h264 --crf=16 \\
  --props='{"disclaimer":"Your wording here."}'
\`\`\`

**Have this line signed off by counsel before the spot runs.** It is the only
copy in the piece with legal exposure, and the default is a placeholder.

---

## 4. Loudness

Target: **−16 LUFS integrated, true peak ≤ −1 dBTP.**

The voice-over file is never normalised. The single master gain lives in
\`src/audio/Soundtrack.tsx\` as \`VO_GAIN\`. Measure with:

\`\`\`bash
npx remotion ffmpeg -i out/aa40_9x16.mp4 -map 0:a -vn \\
  -af loudnorm=I=-16:TP=-1:LRA=11:print_format=json -f null -
\`\`\`

(Remotion's bundled ffmpeg is built with a small filter whitelist that has
no \`ebur128\`; \`loudnorm\` in print mode reports the same measurements.)

Once a music bed is added, re-measure and reset \`VO_GAIN\` — the current
value was measured against voice alone.

---

## 5. Re-rendering after a new \`vo.mp3\`

Drop the new take at \`assets-in/vo.mp3\`, then:

\`\`\`bash
node scripts/scan-assets.mjs      # copies assets-in/ -> public/, writes src/assets.ts
node scripts/transcribe.mjs       # whisper.cpp medium.en, word-level timestamps
node scripts/render-all.mjs       # all six videos + both thumbnails
node scripts/write-readme.mjs     # regenerates this file
\`\`\`

**Nothing else needs editing.** \`src/timing/beats.ts\` looks every sync point
up by word from \`src/timing/vo-words.json\`, and the composition duration is
\`t.end + ${END_HOLD}s\`, so a longer or shorter read re-times the whole spot
including its length.

### Individual render commands

\`\`\`bash
# Full, with audio
npx remotion render AA40-9x16 out/aa40_9x16.mp4 --codec=h264 --crf=16 --audio-bitrate=320k
npx remotion render AA40-16x9 out/aa40_16x9.mp4 --codec=h264 --crf=16 --audio-bitrate=320k

# Overlay, alpha, muted
npx remotion render AA40-9x16-overlay out/aa40_9x16_alpha.mov  --codec=prores --prores-profile=4444 --image-format=png --pixel-format=yuva444p10le --muted
npx remotion render AA40-9x16-overlay out/aa40_9x16_alpha.webm --codec=vp9    --pixel-format=yuva420p --image-format=png --muted
npx remotion render AA40-16x9-overlay out/aa40_16x9_alpha.mov  --codec=prores --prores-profile=4444 --image-format=png --pixel-format=yuva444p10le --muted
npx remotion render AA40-16x9-overlay out/aa40_16x9_alpha.webm --codec=vp9    --pixel-format=yuva420p --image-format=png --muted

# Thumbnails
npx remotion still AA40-9x16 out/thumb_9x16.png --frame=${f(t.end + 1.4)}
npx remotion still AA40-16x9 out/thumb_16x9.png --frame=${f(t.end + 1.4)}
\`\`\`

CRF is passed per-command, never in \`remotion.config.ts\`: it is an
H.264/VP9 setting and ProRes rejects it outright.

On a headless box, add
\`--browser-executable=<path to chrome-headless-shell>\`.

### QA

\`\`\`bash
node scripts/print-beats.mjs 30            # sync map -> qa/sync-map.json
node scripts/qa-sync.mjs out/aa40_9x16.mp4 # hit frames -> qa/sync/
node scripts/qa-frames.mjs AA40-9x16 1 100 245 385   # arbitrary frames -> qa/frames/
node scripts/qa-alpha.mjs                  # pix_fmt + alpha mattes -> qa/alpha/
\`\`\`
`;

fs.mkdirSync(path.join(ROOT, 'out'), {recursive: true});
fs.writeFileSync(path.join(ROOT, 'out', 'README.md'), md);
console.log('[readme] wrote out/README.md');
console.log(`[readme] timing source: ${timingSource}, duration ${fmt(TOTAL_SEC)}`);
console.log(`[readme] placeholders: ${ASSET_NOTES.length}`);
void ASSETS;
