#!/usr/bin/env node
/**
 * Reads `assets-in/`, copies what it finds into `public/`, and regenerates
 * `src/brand.generated.ts` (and, through `vendor-fonts.mjs`, `src/font.ts`).
 *
 *   node scripts/prepare-assets.mjs      (or: npm run assets)
 *
 * Nothing here is required — every input has a documented default, and the
 * script reports exactly which placeholders are still in play so the render
 * report can be honest about it.
 *
 *   assets-in/vo.mp3        final voice-over      -> fallback timing table
 *   assets-in/logo.svg|png  wordmark              -> typographic wordmark
 *   assets-in/brand.json    {font, gold, ink}     -> spec §3 defaults
 *   assets-in/reference.mp4 style reference       -> spec §2 as written
 *   assets-in/broll/*.mp4   legibility QA only    -> flat plates in QA
 */

import {execFileSync} from 'node:child_process';
import {copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const inDir = resolve(root, 'assets-in');
const pubDir = resolve(root, 'public');

const DEFAULTS = {font: 'Manrope', gold: '#E4B85A', ink: '#0B1220'};

mkdirSync(pubDir, {recursive: true});
mkdirSync(inDir, {recursive: true});

const found = [];
const placeholders = [];

/* brand.json ------------------------------------------------------- */
let brand = {...DEFAULTS};
const brandPath = resolve(inDir, 'brand.json');
if (existsSync(brandPath)) {
  try {
    const parsed = JSON.parse(readFileSync(brandPath, 'utf8'));
    brand = {
      font: typeof parsed.font === 'string' && parsed.font.trim() ? parsed.font.trim() : DEFAULTS.font,
      gold: /^#[0-9a-f]{6}$/i.test(parsed.gold ?? '') ? parsed.gold : DEFAULTS.gold,
      ink: /^#[0-9a-f]{6}$/i.test(parsed.ink ?? '') ? parsed.ink : DEFAULTS.ink,
    };
    copyFileSync(brandPath, resolve(pubDir, 'brand.json'));
    found.push(`brand.json  -> font "${brand.font}", gold ${brand.gold}, ink ${brand.ink}`);
  } catch (err) {
    placeholders.push(`brand.json could not be parsed (${err.message}) — using §3 defaults`);
  }
} else {
  placeholders.push('brand colours + typeface: spec §3 defaults (Manrope / #E4B85A / #0B1220)');
}

/* logo ------------------------------------------------------------- */
let logo = null;
for (const name of ['logo.svg', 'logo.png', 'logo.webp']) {
  const p = resolve(inDir, name);
  if (existsSync(p)) {
    copyFileSync(p, resolve(pubDir, name));
    logo = name;
    found.push(`${name}  -> public/${name}`);
    break;
  }
}
if (!logo) {
  placeholders.push('wordmark: typographic (AWESOME white 800 / ATTORNEYS gold 800), no logo supplied');
}

/* voice-over ------------------------------------------------------- */
const voPath = resolve(inDir, 'vo.mp3');
const hasVo = existsSync(voPath);
if (hasVo) {
  copyFileSync(voPath, resolve(pubDir, 'vo.mp3'));
  found.push('vo.mp3  -> public/vo.mp3  (run `npm run vo` to derive timing)');
} else {
  placeholders.push('timing: spec §4.2 fallback table — no vo.mp3 to transcribe');
}

/* reference / b-roll ---------------------------------------------- */
if (existsSync(resolve(inDir, 'reference.mp4'))) {
  found.push('reference.mp4 present — build a contact sheet before design changes');
} else {
  placeholders.push('style reference: spec §2 followed as written, no reference.mp4');
}
const brollDir = resolve(inDir, 'broll');
if (existsSync(brollDir) && readdirSync(brollDir).some((f) => f.endsWith('.mp4'))) {
  found.push('broll/*.mp4 present — QA will composite over it as well as flat plates');
} else {
  placeholders.push('legibility QA: flat grey / white / near-black plates only, no b-roll supplied');
}

/* write brand.generated.ts ---------------------------------------- */
const source = `/**
 * GENERATED by \`node scripts/prepare-assets.mjs\` — do not edit by hand.
 *
 * Re-run that script after dropping files into \`assets-in/\`; it copies them
 * into \`public/\` and rewrites this file from \`assets-in/brand.json\`.
 */

export const BRAND = {
  /** Google Font family name. Must expose weights 500, 700 and 800. */
  font: '${brand.font}',
  gold: '${brand.gold}',
  ink: '${brand.ink}',
  /** public/ filename when a logo is supplied, else null. */
  logo: ${logo ? `'${logo}'` : 'null'} as string | null,
  /** True when assets-in/vo.mp3 was copied into public/. */
  hasVoiceOver: ${hasVo},
} as const;
`;
writeFileSync(resolve(root, 'src/brand.generated.ts'), source);

/* fonts ------------------------------------------------------------ */
execFileSync('node', [resolve(root, 'scripts/vendor-fonts.mjs')], {cwd: root, stdio: 'inherit'});

console.log('\n--- assets found ---');
if (found.length === 0) console.log('  (none — assets-in/ is empty)');
found.forEach((f) => console.log(`  ${f}`));
console.log('\n--- placeholders still in use ---');
placeholders.forEach((p) => console.log(`  ${p}`));
console.log('');
