#!/usr/bin/env node
/**
 * Vendors the project's typeface into `public/fonts/` and rewrites `src/font.ts`
 * to load it from there.
 *
 * The family name and the woff2 URLs still come from `@remotion/google-fonts`
 * (so this stays a Google Font, correctly versioned), but the render itself
 * reads the file off disk. That makes every render offline-safe, byte-identical
 * between machines, and immune to a CDN hiccup half way through 540 frames.
 *
 *   node scripts/vendor-fonts.mjs
 *
 * Re-run it after changing `font` in `assets-in/brand.json` (or just run
 * `npm run assets`, which calls this for you).
 */

import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {mkdirSync, writeFileSync, existsSync, readFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** weights the design system uses: 800 hero, 700 URL, 500 labels */
const WEIGHTS = ['500', '700', '800'];
const SUBSET = 'latin';

const readBrandFont = () => {
  const brandPath = resolve(root, 'assets-in/brand.json');
  if (!existsSync(brandPath)) return 'Manrope';
  try {
    const brand = JSON.parse(readFileSync(brandPath, 'utf8'));
    return typeof brand.font === 'string' && brand.font.trim() ? brand.font.trim() : 'Manrope';
  } catch {
    return 'Manrope';
  }
};

const family = readBrandFont();
// @remotion/google-fonts module names strip spaces: "Inter Tight" -> "InterTight"
const importName = family.replace(/\s+/g, '');

// Reached by path rather than by specifier: the package's `exports` map does
// not expose per-family subpaths.
const metaPath = resolve(
  root,
  'node_modules/@remotion/google-fonts/dist/cjs',
  `${importName}.js`,
);

let info;
try {
  info = require(metaPath).getInfo();
} catch (err) {
  console.error(
    `[vendor-fonts] could not read "${family}" from @remotion/google-fonts ` +
      `(looked for ${importName}.js).\n` +
      `Check the spelling in assets-in/brand.json, or drop a woff2 in public/fonts/ by hand.\n` +
      String(err),
  );
  process.exit(1);
}

const outDir = resolve(root, 'public/fonts');
mkdirSync(outDir, {recursive: true});

// A variable font serves every weight from one file, so download by URL and
// dedupe — Manrope ends up as a single 40 kB file for all three weights.
const byUrl = new Map();
const available = info.fonts.normal ?? {};
for (const weight of WEIGHTS) {
  const url = available[weight]?.[SUBSET];
  if (!url) {
    console.error(`[vendor-fonts] ${family} has no ${SUBSET} weight ${weight}.`);
    process.exit(1);
  }
  if (!byUrl.has(url)) {
    byUrl.set(url, {file: null, weights: []});
  }
  byUrl.get(url).weights.push(weight);
}

let index = 0;
for (const [url, entry] of byUrl) {
  const suffix = byUrl.size === 1 ? SUBSET : `${SUBSET}-${entry.weights.join('_')}`;
  entry.file = `${importName}-${suffix}.woff2`;
  const dest = resolve(outDir, entry.file);
  // curl reads the session's CA configuration; Node's fetch does not.
  execFileSync('curl', ['-sSfL', url, '-o', dest], {stdio: 'inherit'});
  console.log(`[vendor-fonts] ${entry.file}  <-  ${url}`);
  index += 1;
}

const faces = WEIGHTS.map((weight) => {
  const entry = [...byUrl.values()].find((e) => e.weights.includes(weight));
  return `  loadFont({
    family: FONT,
    url: staticFile('fonts/${entry.file}'),
    weight: '${weight}',
    style: 'normal',
    format: 'woff2',
  }),`;
}).join('\n');

const source = `/**
 * GENERATED by \`node scripts/vendor-fonts.mjs\` — do not edit by hand.
 *
 * ${family} ${info.version}, ${SUBSET} subset, weights ${WEIGHTS.join(' / ')}
 * (800 hero, 700 URL, 500 labels — the only weights the design system uses).
 *
 * The file is vendored into \`public/fonts/\` so a render never touches the
 * network. \`delayRender()\` is held until every face has resolved, so no frame
 * is ever rasterised with a fallback face (spec §6).
 */

import {loadFont} from '@remotion/fonts';
import {cancelRender, continueRender, delayRender, staticFile} from 'remotion';

export const FONT = '${family}';

const handle = delayRender('Loading ${family}');

export const fontReady = Promise.all([
${faces}
])
  .then(() => {
    continueRender(handle);
  })
  .catch((err) => {
    cancelRender(err);
  });

/** Applied to every text node in the piece. */
export const TYPE_BASE = {
  fontFamily: FONT,
  fontKerning: 'normal',
  fontVariantLigatures: 'none',
  // Sub-pixel positions are deliberate — never snap type to whole pixels
  // mid-motion (spec §6).
  WebkitFontSmoothing: 'antialiased',
  textRendering: 'geometricPrecision',
  whiteSpace: 'nowrap',
} as const;
`;

writeFileSync(resolve(root, 'src/font.ts'), source);
console.log(`[vendor-fonts] wrote src/font.ts (${family}, ${index} file(s))`);
