#!/usr/bin/env node
/**
 * Vendors the project's typefaces into `public/fonts/` and rewrites
 * `src/font.ts` to load them from there.
 *
 * Two families:
 *   - the kinetic typeface (Manrope by default, or `font` in brand.json) —
 *     weights 500 / 700 / 800, the whole spot outside the end card;
 *   - a display serif (Playfair Display) used only for the end card's
 *     "Get Matched. Get Paid." line.
 *
 * The family names and the woff2 URLs still come from `@remotion/google-fonts`
 * (so these stay correctly-versioned Google Fonts), but the render reads the
 * files off disk. That makes every render offline-safe, byte-identical between
 * machines, and immune to a CDN hiccup half way through 540 frames.
 *
 *   node scripts/vendor-fonts.mjs
 */

import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {mkdirSync, writeFileSync, existsSync, readFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const SUBSET = 'latin';

const readBrandFont = () => {
  const brandPath = resolve(root, 'assets-in/brand.json');
  if (!existsSync(brandPath)) return 'Manrope';
  try {
    const brand = JSON.parse(readFileSync(brandPath, 'utf8'));
    return typeof brand.font === 'string' && brand.font.trim() ? brand.font.trim() : 'Manrope';
  } catch {
    return 'Manrope';
  }
};

/** `export const` name -> family + the weights the design system uses. */
const FAMILIES = [
  {constName: 'FONT', family: readBrandFont(), weights: ['500', '700', '800']},
  {constName: 'SERIF', family: 'Playfair Display', weights: ['500', '600']},
];

const outDir = resolve(root, 'public/fonts');
mkdirSync(outDir, {recursive: true});

const blocks = [];
const faceLines = [];

for (const {constName, family, weights} of FAMILIES) {
  // @remotion/google-fonts module names strip spaces: "Playfair Display" -> "PlayfairDisplay".
  const importName = family.replace(/\s+/g, '');
  // Reached by path rather than by specifier: the package's `exports` map does
  // not expose per-family subpaths.
  const metaPath = resolve(root, 'node_modules/@remotion/google-fonts/dist/cjs', `${importName}.js`);

  let info;
  try {
    info = require(metaPath).getInfo();
  } catch (err) {
    console.error(
      `[vendor-fonts] could not read "${family}" from @remotion/google-fonts ` +
        `(looked for ${importName}.js).\n${String(err)}`,
    );
    process.exit(1);
  }

  // A variable font serves every weight from one file, so download by URL and
  // dedupe — Manrope ends up as a single ~25 kB file for all three weights.
  const byUrl = new Map();
  const available = info.fonts.normal ?? {};
  for (const weight of weights) {
    const url = available[weight]?.[SUBSET];
    if (!url) {
      console.error(`[vendor-fonts] ${family} has no ${SUBSET} weight ${weight}.`);
      process.exit(1);
    }
    if (!byUrl.has(url)) byUrl.set(url, {file: null, weights: []});
    byUrl.get(url).weights.push(weight);
  }

  for (const [url, entry] of byUrl) {
    const suffix = byUrl.size === 1 ? SUBSET : `${SUBSET}-${entry.weights.join('_')}`;
    entry.file = `${importName}-${suffix}.woff2`;
    execFileSync('curl', ['-sSfL', url, '-o', resolve(outDir, entry.file)], {stdio: 'inherit'});
    console.log(`[vendor-fonts] ${entry.file}  <-  ${url}`);
  }

  blocks.push(`export const ${constName} = '${family}';`);
  for (const weight of weights) {
    const entry = [...byUrl.values()].find((e) => e.weights.includes(weight));
    faceLines.push(`  loadFont({
    family: ${constName},
    url: staticFile('fonts/${entry.file}'),
    weight: '${weight}',
    style: 'normal',
    format: 'woff2',
  }),`);
  }
}

const source = `/**
 * GENERATED by \`node scripts/vendor-fonts.mjs\` — do not edit by hand.
 *
 * ${FAMILIES.map((f) => `${f.family} (${f.weights.join(' / ')})`).join(', ')}, ${SUBSET} subset.
 *
 * Both are vendored into \`public/fonts/\` so a render never touches the
 * network. \`delayRender()\` is held until every face has resolved, so no frame
 * is ever rasterised with a fallback face (spec §6).
 */

import {loadFont} from '@remotion/fonts';
import {cancelRender, continueRender, delayRender, staticFile} from 'remotion';

${blocks.join('\n')}

const handle = delayRender('Loading typefaces');

export const fontReady = Promise.all([
${faceLines.join('\n')}
])
  .then(() => {
    continueRender(handle);
  })
  .catch((err) => {
    cancelRender(err);
  });

/** Applied to every text node in the piece. */
export const TYPE_BASE = {
  fontFamily: FONT,
  fontKerning: 'normal',
  fontVariantLigatures: 'none',
  // Sub-pixel positions are deliberate — never snap type to whole pixels
  // mid-motion (spec §6).
  WebkitFontSmoothing: 'antialiased',
  textRendering: 'geometricPrecision',
  whiteSpace: 'nowrap',
} as const;

/** The end card's display serif. */
export const SERIF_BASE = {
  ...TYPE_BASE,
  fontFamily: SERIF,
} as const;
`;

writeFileSync(resolve(root, 'src/font.ts'), source);
console.log(`[vendor-fonts] wrote src/font.ts (${FAMILIES.map((f) => f.family).join(', ')})`);
