/* GENERATED by scripts/scan-assets.mjs — do not edit by hand.
 *
 * Re-run `node scripts/scan-assets.mjs` after dropping files into
 * assets-in/. Components branch on this manifest so a missing asset
 * degrades to its placeholder rather than failing the render.
 */

import type {Brand} from './theme';

export type SfxName = 'stamp' | 'whoosh' | 'connect' | 'slam' | 'rise';

export const ASSETS = {
	vo: 'vo.mp3' as string | null,
	music: null as string | null,
	sfx: {
		stamp: null,
		whoosh: null,
		connect: null,
		slam: null,
		rise: null,
	} as Record<SfxName, string | null>,
	logo: null as string | null,
	brand: null as Brand | null,
} as const;

/** Human-readable list of what is still a placeholder. */
export const ASSET_NOTES: string[] = [
 "music.mp3 MISSING — the <Audio> music slot in src/audio/Soundtrack.tsx is wired but inert (TODO there). Drop a licensed 20s+ bed into assets-in/music.mp3 and re-run this script.",
 "sfx/stamp.wav MISSING — slot wired, nothing rendered",
 "sfx/whoosh.wav MISSING — slot wired, nothing rendered",
 "sfx/connect.wav MISSING — slot wired, nothing rendered",
 "sfx/slam.wav MISSING — slot wired, nothing rendered",
 "sfx/rise.wav MISSING — slot wired, nothing rendered",
 "logo.svg/.png MISSING — using the typographic wordmark",
 "brand.json MISSING — using the §3 palette"
];
