/**
 * Regenerates src/assets.ts from whatever is actually sitting in public/assets.
 * Keeps renders deterministic: a missing photo becomes `null` at build time and
 * the composition falls back to its procedural stand-in instead of failing.
 *
 * Run after dropping new art in: npm run sync-assets
 */
import {existsSync, readdirSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';

const DIR = join(process.cwd(), 'public', 'assets');

/** Logical name -> accepted filenames, most preferred first. */
const WANTED = {
  franklin: ['franklin.jpg', 'franklin.jpeg', 'franklin.png', 'franklin.webp'],
  cashStacks: ['cash-stacks.jpg', 'cash-stacks.png', 'cash-stacks.webp'],
  fallingBills: ['falling-bills.png', 'falling-bills.webp'],
  bill: ['bill.png', 'bill.webp'],
  cart: ['cart.png', 'cart.webp'],
  grandma: ['grandma.png', 'grandma.webp'],
  walmartLogo: ['walmart-logo.png', 'walmart-logo.svg', 'walmart-logo.webp'],
  walmartSpark: ['walmart-spark.png', 'walmart-spark.svg', 'walmart-spark.webp'],
  brandLogo: ['brand-logo.png', 'brand-logo.svg', 'brand-logo.webp'],
};

const present = existsSync(DIR) ? new Set(readdirSync(DIR)) : new Set();

const entries = Object.entries(WANTED).map(([key, candidates]) => {
  const hit = candidates.find((c) => present.has(c));
  return `  ${key}: ${hit ? `'assets/${hit}'` : 'null'},`;
});

const out = `/* AUTO-GENERATED by scripts/sync-assets.mjs — do not edit by hand. */

/**
 * Paths are relative to public/ so they can be passed straight to staticFile().
 * A null entry means the art has not been supplied yet and the composition
 * should render its procedural fallback.
 */
export const ASSETS = {
${entries.join('\n')}
} as const;
`;

writeFileSync(join(process.cwd(), 'src', 'assets.ts'), out);
const found = entries.filter((e) => !e.includes('null')).length;
console.log(`sync-assets: ${found}/${entries.length} assets resolved from public/assets`);
