/**
 * GENERATED by `node scripts/prepare-assets.mjs` — do not edit by hand.
 *
 * Re-run that script after dropping files into `assets-in/`; it copies them
 * into `public/` and rewrites this file from `assets-in/brand.json`.
 */

export const BRAND = {
  /** Google Font family name. Must expose weights 500, 700 and 800. */
  font: 'Manrope',
  gold: '#E4B85A',
  ink: '#0B1220',
  /** public/ filename when a logo is supplied, else null. */
  logo: null as string | null,
  /** True when assets-in/vo.mp3 was copied into public/. */
  hasVoiceOver: false,
} as const;
