/**
 * GENERATED by `node scripts/vendor-fonts.mjs` — do not edit by hand.
 *
 * Manrope v20, latin subset, weights 500 / 700 / 800
 * (800 hero, 700 URL, 500 labels — the only weights the design system uses).
 *
 * The file is vendored into `public/fonts/` so a render never touches the
 * network. `delayRender()` is held until every face has resolved, so no frame
 * is ever rasterised with a fallback face (spec §6).
 */

import {loadFont} from '@remotion/fonts';
import {cancelRender, continueRender, delayRender, staticFile} from 'remotion';

export const FONT = 'Manrope';

const handle = delayRender('Loading Manrope');

export const fontReady = Promise.all([
  loadFont({
    family: FONT,
    url: staticFile('fonts/Manrope-latin.woff2'),
    weight: '500',
    style: 'normal',
    format: 'woff2',
  }),
  loadFont({
    family: FONT,
    url: staticFile('fonts/Manrope-latin.woff2'),
    weight: '700',
    style: 'normal',
    format: 'woff2',
  }),
  loadFont({
    family: FONT,
    url: staticFile('fonts/Manrope-latin.woff2'),
    weight: '800',
    style: 'normal',
    format: 'woff2',
  }),
])
  .then(() => {
    continueRender(handle);
  })
  .catch((err) => {
    cancelRender(err);
  });

/** Applied to every text node in the piece. */
export const TYPE_BASE = {
  fontFamily: FONT,
  fontKerning: 'normal',
  fontVariantLigatures: 'none',
  // Sub-pixel positions are deliberate — never snap type to whole pixels
  // mid-motion (spec §6).
  WebkitFontSmoothing: 'antialiased',
  textRendering: 'geometricPrecision',
  whiteSpace: 'nowrap',
} as const;
