/**
 * GENERATED by `node scripts/vendor-fonts.mjs` — do not edit by hand.
 *
 * Manrope (500 / 700 / 800), Playfair Display (500 / 600), latin subset.
 *
 * Both are vendored into `public/fonts/` so a render never touches the
 * network. `delayRender()` is held until every face has resolved, so no frame
 * is ever rasterised with a fallback face (spec §6).
 */

import {loadFont} from '@remotion/fonts';
import {cancelRender, continueRender, delayRender, staticFile} from 'remotion';

export const FONT = 'Manrope';
export const SERIF = 'Playfair Display';

const handle = delayRender('Loading typefaces');

export const fontReady = Promise.all([
  loadFont({
    family: FONT,
    url: staticFile('fonts/Manrope-latin.woff2'),
    weight: '500',
    style: 'normal',
    format: 'woff2',
  }),
  loadFont({
    family: FONT,
    url: staticFile('fonts/Manrope-latin.woff2'),
    weight: '700',
    style: 'normal',
    format: 'woff2',
  }),
  loadFont({
    family: FONT,
    url: staticFile('fonts/Manrope-latin.woff2'),
    weight: '800',
    style: 'normal',
    format: 'woff2',
  }),
  loadFont({
    family: SERIF,
    url: staticFile('fonts/PlayfairDisplay-latin.woff2'),
    weight: '500',
    style: 'normal',
    format: 'woff2',
  }),
  loadFont({
    family: SERIF,
    url: staticFile('fonts/PlayfairDisplay-latin.woff2'),
    weight: '600',
    style: 'normal',
    format: 'woff2',
  }),
])
  .then(() => {
    continueRender(handle);
  })
  .catch((err) => {
    cancelRender(err);
  });

/** Applied to every text node in the piece. */
export const TYPE_BASE = {
  fontFamily: FONT,
  fontKerning: 'normal',
  fontVariantLigatures: 'none',
  // Sub-pixel positions are deliberate — never snap type to whole pixels
  // mid-motion (spec §6).
  WebkitFontSmoothing: 'antialiased',
  textRendering: 'geometricPrecision',
  whiteSpace: 'nowrap',
} as const;

/** The end card's display serif. */
export const SERIF_BASE = {
  ...TYPE_BASE,
  fontFamily: SERIF,
} as const;
