/* AUTO-GENERATED by scripts/sync-assets.mjs — do not edit by hand. */

/**
 * Paths are relative to public/ so they can be passed straight to staticFile().
 * A null entry means the art has not been supplied yet and the composition
 * should render its procedural fallback.
 */
export const ASSETS = {
  franklin: null,
  cashStacks: null,
  fallingBills: null,
  cart: null,
  grandma: null,
  walmartLogo: null,
  walmartSpark: null,
} as const;
